//<auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace User.Module.Infrastructure.DataBase.Migrations
{
    /// <inheritdoc />
    public partial class ChangeSchemaToUsers : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "users");

            migrationBuilder.RenameTable(
                name: "outbox_messages",
                schema: "user",
                newName: "outbox_messages",
                newSchema: "users");

            migrationBuilder.RenameTable(
                name: "outbox_message_consumers",
                schema: "user",
                newName: "outbox_message_consumers",
                newSchema: "users");

            migrationBuilder.RenameTable(
                name: "event_user",
                schema: "user",
                newName: "event_user",
                newSchema: "users");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "user");

            migrationBuilder.RenameTable(
                name: "outbox_messages",
                schema: "users",
                newName: "outbox_messages",
                newSchema: "user");

            migrationBuilder.RenameTable(
                name: "outbox_message_consumers",
                schema: "users",
                newName: "outbox_message_consumers",
                newSchema: "user");

            migrationBuilder.RenameTable(
                name: "event_user",
                schema: "users",
                newName: "event_user",
                newSchema: "user");
        }
    }
}
